directories:
  output: release
  buildResources: build
appId: zoo.grandemaison.gme
productName: GME
copyright: © 2026 Grandemaison
files:
  - filter:
      - dist/**/*
      - electron/**/*
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: public/icon.ico
mac:
  target:
    - target: dmg
      arch:
        - x64
        - arm64
  icon: public/icon.icns
  category: public.app-category.graphics-design
linux:
  target:
    - target: AppImage
      arch:
        - x64
  icon: public/icon.png
  category: Graphics
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
publish:
  provider: generic
  url: https://grandemaisonzoo.com/gme/
electronVersion: 42.0.1
